name: Android CI

on:
  push:
    branches: [ "rewrite" ]
  pull_request:
    branches: [ "rewrite" ]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Build manually'
        required: true
        default: 'development'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        ref: 'rewrite'
        submodules: 'recursive'
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    #- name: Setup Android NDK
     # uses: nttld/setup-ndk@v1.5.0
      #with:
       # ndk-version: 

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name : Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: build-artifact
        path: app/build/outputs/apk/debug/app-debug.apk
